swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json
basePath: /api
paths:
  /graph:
    post:
      operationId: api.graph.get_data
      tags:
        - data
      summary: data
      description: data
      parameters:
          - in: body
            name: body
            required: true
            schema:
              type: object
      responses:
        200:
          description: Successfully retrieved the data